   // List your images here
   const images = [
    "images/Aligator.png",
    "images/Auto.png",
    "images/Beba.png",
    "images/Buba mara.png",
    "images/Cvet.png",
    "images/Daljinski.png",
    "images/Drvo.png",
    "images/Duda.png",
    "images/Dva.png",
    "images/Earth.png",
    "images/Frizider.png",
    "images/Galaksija.png",
    "images/Hippo.png",
    "images/Jabuka.png",
    "images/Jupiter.png",
    "images/Kafa.png",
    "images/Kasika.png",
    "images/Krava.png",
    "images/Kuca.png",
    "images/Lav 1.png",
    "images/Lav.png",
    "images/Leptir.png",
    "images/Lopta.png",
    "images/Maca.png",
    "images/Mars.png",
    "images/Meda.png",
    "images/Mercury.png",
    "images/Mis.png",
    "images/Moon.png",
    "images/Neptune.png",
    "images/Noga.png",
    "images/Noz.png",
    "images/Oko.png",
    "images/One.png",
    "images/Pantalone.png",
    "images/Raketa.png",
    "images/Robot.png",
    "images/Saturn.png",
    "images/Slon.png",
    "images/Sova.png",
    "images/Sunce.png",
    "images/Sunce1.png",
    "images/Tesla.png",
    "images/Uran.png",
    "images/Venus.png",
    "images/Viljuska.png",
    "images/Voda.png",
    "images/Zmija.png",
    "images/zebra.png",
  ];
  