import os

# ===== CONFIG =====
IMAGE_FOLDER = os.path.join(os.path.dirname(__file__), "images")
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "images.js")
VALID_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
# ==================

"""
This script generates a JavaScript dictionary of images in the images folder with their first letter and first two letters.

The output is a JavaScript dictionary variable of images and their first letter and first two letters as other keys.

The output is saved to the images.js file.

"""
files = sorted(os.listdir(IMAGE_FOLDER))

image_files = [
    f for f in files
    if os.path.splitext(f)[1].lower() in VALID_EXTENSIONS
]

with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    f.write("   // The images dictionary is generated by the generate_js_images_dict.py script.\n")
    f.write("   const images = [\n")
    
    for image in image_files:
        # Extract filename without extension
        filename = os.path.splitext(image)[0]
        
        # Get first letter and first two letters
        first_letter = filename[0] if len(filename) >= 1 else ""
        first_two_letters = filename[:2] if len(filename) >= 2 else filename
        whole_word = filename
        if " " in filename:
            whole_word = filename.split(" ")[0]
        if any(char.isdigit() for char in whole_word):
            whole_word = "".join(char for char in whole_word if not char.isdigit())
        # END: if the whole word has a number in it, remove the number
        
        # Write the dictionary entry
        f.write(f'    {{ path: "images/{image}", firstLetter: "{first_letter}", firstTwoLetters: "{first_two_letters}", wholeWord: "{whole_word}" }},\n')
    
    f.write("  ];\n")
    f.write("\n")

print(f"Generated {OUTPUT_FILE} with {len(image_files)} images.")
